name: test-build
on:
  push:
    branches: [main, dev]
  pull_request:
jobs:
  flatpak-builder:
    name: "Flatpak build"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: webex.flatpak
        manifest-path: com.cisco.Webex.yaml
        cache-key: flatpak-builder-${{ github.sha }}
