# webex .deb update checker

name: Check for webex .deb updates
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}
jobs:
  webex-bin-update-checker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ main, dev ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - name: Setup tools
        run: |
          sudo apt update
          sudo apt install -y xmlstarlet
      - name: Get previous .deb checksum 
        id: prevdeb
        uses: mikefarah/yq@master
        with:
          cmd: >
            yq '.modules[2].sources[0].sha256' com.cisco.Webex.yaml
      - name: Download latest .deb & get its metadata
        id: newdeb
        run: |
          curl -O https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb
          SIZE=$(du -b Webex.deb | awk '{print $1}')
          CHECKSUM=$(sha256sum Webex.deb | awk '{print $1}')
          DATE=$(date +'%Y-%m-%d')
          VERSION=$(bsdtar -Oxf Webex.deb 'control.tar.gz' | bsdtar -Oxf - control | grep Version | awk '{print $2}')
          echo "::set-output name=size::$SIZE"
          echo "::set-output name=checksum::$CHECKSUM"
          echo "::set-output name=date::$DATE"
          echo "::set-output name=version::$VERSION"
      - name: Update checksum & filesize in manifest yaml
        if: steps.prevdeb.outputs.result != steps.newdeb.outputs.checksum
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.modules[2].sources[0].sha256 = "${{ steps.newdeb.outputs.checksum }}"' com.cisco.Webex.yaml
            yq -i '.modules[2].sources[0].size = ${{ fromJSON(steps.newdeb.outputs.size) }}' com.cisco.Webex.yaml
      - name: Update version & release date in metainfo XML
        if: steps.prevdeb.outputs.result != steps.newdeb.outputs.checksum
        run: >
          xmlstarlet ed -L
            -i '/component/releases/release[1]' -t elem -n release -v
            -i '/component/releases/release[1]' -t attr -n version
              -v "${{ steps.newdeb.outputs.version }}"
            -i '/component/releases/release[1]' -t attr -n date
              -v "${{ steps.newdeb.outputs.date }}"
            com.cisco.Webex.metainfo.xml
      - name: Create pull request
        if: steps.prevdeb.outputs.result != steps.newdeb.outputs.checksum
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: webex-deb-update
          title: Update webex.deb to ${{ steps.newdeb.outputs.version }}
          body: This pull request was automatically generated by webex .deb updater. Please open an issue if you have any questions or complaints.
