name: Check for webex binary updates
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}
jobs:
  webex-bin-update-checker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ dev ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - name: Get previous binary checksum 
        id: prevbin
        uses: mikefarah/yq@master
        with:
          cmd: yq '.modules[] | select(.name == "webex").sources[] | select(.filename == "webex.deb").sha256' com.cisco.Webex.yaml
      - name: Download latest binary & get its checksum, size
        id: newbin
        run: |
          curl -O https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb
          FILESIZE=$(du -b Webex.deb | awk '{print $1}')
          echo '::set-output name=size::$FILESIZE'
          echo "::set-output name=result::${{ hashFiles('Webex.deb') }}"
      - uses: mikefarah/yq@master
      - name: Compare two checksums and update if they are different
        if: ${{ steps.prevbin.outputs.result }} != ${{ steps.newbin.outputs.result }}
        run: |
            yq e '.modules[2].sources[0].sha256 = "${{ steps.newbin.outputs.result }}"' -i com.cisco.Webex.yaml
            yq e '.modules[2].sources[0].size = "${{ fromJSON(steps.newbin.outputs.size) }}"' -i com.cisco.Webex.yaml
      - name: Create pull request
        if: ${{ steps.prevbin.outputs.result }} != ${{ steps.newbin.outputs.result }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update webex binary
